export enum AdminLogAction {
    REGISTER_ACCEPTION = 'REGISTER_ACCEPTION',
    ACCOUNT_MANAGE = 'ACCOUNT_MANAGE',
    SEASON_MANAGE = 'SEASON_MANAGE',
    TRAINING_TYPE_MANAGE = 'TRAINING_TYPE_MANAGE',
    TRAINING_MANAGE = 'TRAINING_MANAGE',
    TALENT_ASSIGNMENT = 'TALENT_ASSIGNMENT',
    NOTICE = 'NOTICE',
}